### ISSUE TITLE
create_synthetic_dataset.py running wrong

### ISSUE THREAD

**Issue by songyukino1** [JuliaWolleb/DeScarGAN#6]
I run the _create_synthetic_dataset.py_ want to produce dataset, but it wrong at 
Traceback (most recent call last):
  File "/home/songyuqi/workspace/pytorch/DeScarGAN/create_synthetic_dataset.py", line 167, in <module>
    x3, y3 = intersections(a3, b3)
  File "/home/songyuqi/workspace/pytorch/DeScarGAN/create_synthetic_dataset.py", line 161, in intersections
    x = [p.x for p in mp]
TypeError: 'LineString' object is not iterable

Process finished with exit code 1

could you help me fix it?

**Comment by songyukino1** [comment]
my envirment:
certifi           2020.11.8
cycler            0.10.0
joblib            0.17.0
kiwisolver        1.3.0
matplotlib        3.3.2
mkl-fft           1.2.0
mkl-random        1.1.1
mkl-service       2.3.0
numpy             1.19.2
olefile           0.46
Pillow            8.0.1
pip               20.2.4
pyparsing         2.4.7
python-dateutil   2.8.1
scikit-learn      0.23.2
scipy             1.5.4
setuptools        50.3.1.post20201107
Shapely           1.7.1
sip               4.19.13
six               1.15.0
threadpoolctl     2.1.0
torch             1.7.0
torchaudio        0.7.0a0+ac17b64
torchvision       0.8.1
tornado           6.0.4
typing-extensions 3.7.4.3
wheel             0.35.1

**Comment by JuliaWolleb** [comment]
Hello


I guess the problem lies somewhere in the shapely package. I have shapely version 1.6.4. Could you try with that?

________________________________
Von: songyukino1 <notifications@github.com>
Gesendet: Donnerstag, 26. November 2020 11:42:41
An: JuliaWolleb/DeScarGAN
Cc: Subscribed
Betreff: Re: [JuliaWolleb/DeScarGAN] create_synthetic_dataset.py running wrong (#6)


my envirment:
certifi 2020.11.8
cycler 0.10.0
joblib 0.17.0
kiwisolver 1.3.0
matplotlib 3.3.2
mkl-fft 1.2.0
mkl-random 1.1.1
mkl-service 2.3.0
numpy 1.19.2
olefile 0.46
Pillow 8.0.1
pip 20.2.4
pyparsing 2.4.7
python-dateutil 2.8.1
scikit-learn 0.23.2
scipy 1.5.4
setuptools 50.3.1.post20201107
Shapely 1.7.1
sip 4.19.13
six 1.15.0
threadpoolctl 2.1.0
torch 1.7.0
torchaudio 0.7.0a0+ac17b64
torchvision 0.8.1
tornado 6.0.4
typing-extensions 3.7.4.3
wheel 0.35.1

**Comment by songyukino1** [comment]
ok, i fix the bug.
        def intersections(a, b):
            ea = LinearRing(a)
            eb = LinearRing(b)
            mp = ea.intersection(eb)
            **mp = np.array(mp)**
            x = [p.x for p in mp]
            y = [p.y for p in mp]
            return x, y

and if someone need to product 2000 dataset,
you need to change follow:
1, 
for num in range(4000):
  if count<2000:            #create a dataset of 2000 images
orginal: count<20
2,
the last area of code:
remove if-else and change str(num) to str(count)

Thanks!
